
@startuml
/'
通过修改活动标签最后的分号分隔符 (;),可以为活动设置不同的形状。
• |
• <
• >
• /
• ]
• }'/
:Ready;
:next(o)|
:Receiving;
split
:nak(i)<
:ack(o)>
split again
:ack(i)<
:next(o)
on several line|
:i := i + 1]
:ack(o)>
split again
:err(i)<
:nak(o)>
split again
:foo/
split again
:i > 5}
stop
end split
:finish;
@enduml