insert into episodes values(0, NULL, "Good News Bad News");
insert into episodes values(1, 1, "Male Unbonding");
insert into episodes values(2, 1, "The Stake Out");
insert into episodes values(3, 1, "The Robbery");
insert into episodes values(4, 1, "The Stock Tip");
insert into episodes values(5, 2, "The Ex-Girlfriend");
insert into episodes values(6, 2, "The Pony Remark");
insert into episodes values(7, 2, "The Busboy");
insert into episodes values(8, 2, "The Baby Shower");
insert into episodes values(9, 2, "The Jacket");
insert into episodes values(10, 2, "The Chinese Restaurant");
insert into episodes values(11, 2, "The Phone Message");
insert into episodes values(12, 2, "The Apartment");
insert into episodes values(13, 2, "The Stranded");
insert into episodes values(14, 2, "The Statue");
insert into episodes values(15, 2, "The Heart Attack");
insert into episodes values(16, 2, "The Revenge");
insert into episodes values(17, 2, "The Deal");
insert into episodes values(18, 3, "The Note");
insert into episodes values(19, 3, "The Truth");
insert into episodes values(20, 3, "The Dog");
insert into episodes values(21, 3, "The Library");
insert into episodes values(22, 3, "The Pen");
insert into episodes values(23, 3, "The Parking Garage");
insert into episodes values(24, 3, "The Cafe");
insert into episodes values(25, 3, "The Tape");
insert into episodes values(26, 3, "The Nose Job");
insert into episodes values(27, 3, "The Alternate Side");
insert into episodes values(28, 3, "The Red Dot");
insert into episodes values(29, 3, "The Suicide");
insert into episodes values(30, 3, "The Subway");
insert into episodes values(31, 3, "The Pez Dispenser");
insert into episodes values(32, 3, "The Boyfriend 1");
insert into episodes values(33, 3, "The Boyfriend 2");
insert into episodes values(34, 3, "The Fix Up");
insert into episodes values(35, 3, "The Limo");
insert into episodes values(36, 3, "The Good Samaritan");
insert into episodes values(37, 3, "The Letter");
insert into episodes values(38, 3, "The Parking Space");
insert into episodes values(39, 3, "The Keys");
insert into episodes values(40, 4, "The Trip 1");
insert into episodes values(41, 4, "The Trip 2");
insert into episodes values(42, 4, "The Pitch");
insert into episodes values(43, 4, "The Ticket");
insert into episodes values(44, 4, "The Wallet");
insert into episodes values(45, 4, "The Watch");
insert into episodes values(46, 4, "The Bubble Boy");
insert into episodes values(47, 4, "The Cheever Letters");
insert into episodes values(48, 4, "The Opera");
insert into episodes values(49, 4, "The Virgin");
insert into episodes values(50, 4, "The Contest");
insert into episodes values(51, 4, "The Airport");
insert into episodes values(52, 4, "The Pick");
insert into episodes values(53, 4, "The Movie");
insert into episodes values(54, 4, "The Visa");
insert into episodes values(55, 4, "The Shoes");
insert into episodes values(56, 4, "The Outing");
insert into episodes values(57, 4, "The Old Man");
insert into episodes values(58, 4, "The Implant");
insert into episodes values(59, 4, "The Junior Mint");
insert into episodes values(60, 4, "The Smelly Car");
insert into episodes values(61, 4, "The Handicap Spot");
insert into episodes values(62, 4, "The Pilot 1");
insert into episodes values(63, 4, "The Pilot 2");
insert into episodes values(64, 5, "The Mango");
insert into episodes values(65, 5, "The Puffy Shirt");
insert into episodes values(66, 5, "The Glasses");
insert into episodes values(67, 5, "The Sniffing Accountant");
insert into episodes values(68, 5, "The Bris");
insert into episodes values(69, 5, "The Lip Reader");
insert into episodes values(70, 5, "The Non-Fat Yogurt");
insert into episodes values(71, 5, "The Barber");
insert into episodes values(72, 5, "The Masseuse");
insert into episodes values(73, 5, "The Cigar Store Indian");
insert into episodes values(74, 5, "The Conversion");
insert into episodes values(75, 5, "The Stall");
insert into episodes values(76, 5, "The Dinner Party");
insert into episodes values(77, 5, "The Marine Biologist");
insert into episodes values(78, 5, "The Pie");
insert into episodes values(79, 5, "The Stand-In");
insert into episodes values(80, 5, "The Wife");
insert into episodes values(81, 5, "The Raincoats 1");
insert into episodes values(82, 5, "The Raincoats 2");
insert into episodes values(83, 5, "The Fire");
insert into episodes values(84, 5, "The Hamptons");
insert into episodes values(85, 5, "The Opposite");
insert into episodes values(86, 6, "The Chaperone");
insert into episodes values(87, 6, "The Big Salad");
insert into episodes values(88, 6, "The Pledge Drive");
insert into episodes values(89, 6, "The Chinese Woman");
insert into episodes values(90, 6, "The Couch");
insert into episodes values(91, 6, "The Gymnast");
insert into episodes values(92, 6, "The Soup");
insert into episodes values(93, 6, "The Mom & Pop Store");
insert into episodes values(94, 6, "The Secretary");
insert into episodes values(95, 6, "The Race");
insert into episodes values(96, 6, "The Switch");
insert into episodes values(97, 6, "The Label Maker");
insert into episodes values(98, 6, "The Scofflaw");
insert into episodes values(99, 6, "Highlights of 100 1");
insert into episodes values(100, 6, "Highlights of 100 2");
insert into episodes values(101, 6, "The Beard");
insert into episodes values(102, 6, "The Kiss Hello");
insert into episodes values(103, 6, "The Doorman");
insert into episodes values(104, 6, "The Jimmy");
insert into episodes values(105, 6, "The Doodle");
insert into episodes values(106, 6, "The Fusilli Jerry");
insert into episodes values(107, 6, "The Diplomat''s Club");
insert into episodes values(108, 6, "The Face Painter");
insert into episodes values(109, 6, "The Understudy");
insert into episodes values(110, 7, "The Engagement");
insert into episodes values(111, 7, "The Postponement");
insert into episodes values(112, 7, "The Maestro");
insert into episodes values(113, 7, "The Wink");
insert into episodes values(114, 7, "The Hot Tub");
insert into episodes values(115, 7, "The Soup Nazi");
insert into episodes values(116, 7, "The Secret Code");
insert into episodes values(117, 7, "The Pool Guy");
insert into episodes values(118, 7, "The Sponge");
insert into episodes values(119, 7, "The Gum");
insert into episodes values(120, 7, "The Rye");
insert into episodes values(121, 7, "The Caddy");
insert into episodes values(122, 7, "The Seven");
insert into episodes values(123, 7, "The Cadillac 1");
insert into episodes values(124, 7, "The Cadillac 2");
insert into episodes values(125, 7, "The Shower Head");
insert into episodes values(126, 7, "The Doll");
insert into episodes values(127, 7, "The Friars Club");
insert into episodes values(128, 7, "The Wig Master");
insert into episodes values(129, 7, "The Calzone");
insert into episodes values(130, 7, "The Bottle Deposit 1");
insert into episodes values(131, 7, "The Bottle Deposit 2");
insert into episodes values(132, 7, "The Wait Out");
insert into episodes values(133, 7, "The Invitations");
insert into episodes values(134, 8, "The Foundation");
insert into episodes values(135, 8, "The Soul Mate");
insert into episodes values(136, 8, "The Bizarro Jerry");
insert into episodes values(137, 8, "The Little Kicks");
insert into episodes values(138, 8, "The Package");
insert into episodes values(139, 8, "The Fatigues");
insert into episodes values(140, 8, "The Checks");
insert into episodes values(141, 8, "The Chicken Roaster");
insert into episodes values(142, 8, "The Abstinence");
insert into episodes values(143, 8, "The Andrea Doria");
insert into episodes values(144, 8, "The Little Jerry");
insert into episodes values(145, 8, "The Money");
insert into episodes values(146, 8, "The Comeback");
insert into episodes values(147, 8, "The Van Buren Boys");
insert into episodes values(148, 8, "The Susie");
insert into episodes values(149, 8, "The Pothole");
insert into episodes values(150, 8, "The English Patient");
insert into episodes values(151, 8, "The Nap");
insert into episodes values(152, 8, "The Yada Yada");
insert into episodes values(153, 8, "The Millennium");
insert into episodes values(154, 8, "The Muffin Tops");
insert into episodes values(155, 8, "The Summer of George");
insert into episodes values(156, 9, "The Butter Shave");
insert into episodes values(157, 9, "The Voice");
insert into episodes values(158, 9, "The Serenity Now");
insert into episodes values(159, 9, "The Blood");
insert into episodes values(160, 9, "The Junk Mail");
insert into episodes values(161, 9, "The Merv Griffin Show");
insert into episodes values(162, 9, "The Slicer");
insert into episodes values(163, 9, "The Betrayal");
insert into episodes values(164, 9, "The Apology");
insert into episodes values(165, 9, "The Strike");
insert into episodes values(166, 9, "The Dealership");
insert into episodes values(167, 9, "The Reverse Peephole");
insert into episodes values(168, 9, "The Cartoon");
insert into episodes values(169, 9, "The Strongbox");
insert into episodes values(170, 9, "The Wizard");
insert into episodes values(171, 9, "The Burning");
insert into episodes values(172, 9, "The Bookstore");
insert into episodes values(173, 9, "The Frogger");
insert into episodes values(174, 9, "The Maid");
insert into episodes values(175, 9, "The Puerto Rican Day");
insert into episodes values(176, 9, "The Clip Show 1");
insert into episodes values(177, 9, "The Clip Show 2");
insert into episodes values(178, 9, "The Finale 1");
insert into episodes values(179, 9, "The Finale 2");
insert into episodes values(180, NULL, "Reunion Special:The Seinfeld Story");
