insert into foods values(1, 1, 'Bagels');
insert into foods_episodes values(1, 165);
insert into foods values(2, 1, 'Bagels, raisin');
insert into foods_episodes values(2, 165);
insert into foods_episodes values(2, 154);
insert into foods values(3, 1, 'Bavarian Cream Pie');
insert into foods_episodes values(3, 115);
insert into foods values(4, 1, 'Bear Claws');
insert into foods_episodes values(4, 169);
insert into foods_episodes values(4, 67);
insert into foods_episodes values(4, 82);
insert into foods values(5, 1, 'Black and White cookies');
insert into foods_episodes values(5, 76);
insert into foods_episodes values(5, 109);
insert into foods values(6, 1, 'Bread (with nuts)');
insert into foods_episodes values(6, 164);
insert into foods values(7, 1, 'Butterfingers');
insert into foods_episodes values(7, 66);
insert into foods values(8, 1, 'Carrot Cake');
insert into foods_episodes values(8, 173);
insert into foods values(9, 1, 'Chips Ahoy Cookies');
insert into foods_episodes values(9, 123);
insert into foods values(10, 1, 'Chocolate Bobka');
insert into foods_episodes values(10, 76);
insert into foods values(11, 1, 'Chocolate Eclairs');
insert into foods_episodes values(11, 91);
insert into foods values(12, 1, 'Chocolate Cream Pie');
insert into foods_episodes values(12, 78);
insert into foods values(13, 1, 'Cinnamon Bobka');
insert into foods_episodes values(13, 76);
insert into foods values(14, 1, 'Cinnamon Swirls');
insert into foods_episodes values(14, 66);
insert into foods values(15, 1, 'Cookie');
insert into foods_episodes values(15, 27);
insert into foods values(16, 1, 'Crackers');
insert into foods_episodes values(16, 136);
insert into foods values(17, 1, 'Cupcake');
insert into foods_episodes values(17, 122);
insert into foods values(18, 1, 'Cupcakes');
insert into foods_episodes values(18, 114);
insert into foods values(19, 1, 'Devils Food Cake');
insert into foods_episodes values(19, 171);
insert into foods values(20, 1, 'Dinky Donuts');
insert into foods_episodes values(20, 18);
insert into foods_episodes values(20, 66);
insert into foods values(21, 1, 'Dog biscuits');
insert into foods_episodes values(21, 143);
insert into foods values(22, 1, 'Donuts');
insert into foods_episodes values(22, 169);
insert into foods values(23, 1, 'Drakes Coffee Cakes');
insert into foods_episodes values(23, 29);
insert into foods values(24, 1, 'Entenmann''s Cake');
insert into foods_episodes values(24, 173);
insert into foods values(25, 1, 'Kaiser Rolls');
insert into foods_episodes values(25, 162);
insert into foods values(26, 1, 'Marble Ryes');
insert into foods_episodes values(26, 120);
insert into foods values(27, 1, 'Mini Ritz');
insert into foods_episodes values(27, 9);
insert into foods values(28, 1, 'Muffin');
insert into foods_episodes values(28, 43);
insert into foods values(29, 1, 'Muffin Tops');
insert into foods_episodes values(29, 154);
insert into foods values(30, 1, 'Muffin Stumps');
insert into foods_episodes values(30, 154);
insert into foods values(31, 1, 'Nut Bread');
insert into foods_episodes values(31, 161);
insert into foods values(32, 1, 'Pastries (of the Gods)');
insert into foods_episodes values(32, 14);
insert into foods values(33, 1, 'Peach Muffin');
insert into foods_episodes values(33, 154);
insert into foods values(34, 1, 'Peppridge Farms Cookies (Milanos)');
insert into foods_episodes values(34, 40);
insert into foods values(35, 1, 'Pizza Bagels');
insert into foods_episodes values(35, 154);
insert into foods values(36, 1, 'Pie');
insert into foods_episodes values(36, 75);
insert into foods values(37, 1, 'Pie (blueberry)');
insert into foods_episodes values(37, 46);
insert into foods values(38, 1, 'Pie (Blackberry) Pie');
insert into foods_episodes values(38, 46);
insert into foods values(39, 1, 'Pie (Boysenberry)');
insert into foods_episodes values(39, 46);
insert into foods values(40, 1, 'Pie (Huckleberry)');
insert into foods_episodes values(40, 46);
insert into foods values(41, 1, 'Pie (Raspberry)');
insert into foods_episodes values(41, 46);
insert into foods values(42, 1, 'Pie (Strawberry)');
insert into foods_episodes values(42, 46);
insert into foods values(43, 1, 'Pie (Cranberry)');
insert into foods_episodes values(43, 46);
insert into foods values(44, 1, 'Pie (Peach)');
insert into foods_episodes values(44, 46);
insert into foods values(45, 1, 'Poppy Seed Muffins');
insert into foods_episodes values(45, 125);
insert into foods values(46, 1, 'Triscuits');
insert into foods_episodes values(46, 29);
insert into foods values(47, 1, 'Wedding Cake (Royal)');
insert into foods_episodes values(47, 173);
insert into foods values(48, 2, 'Bran');
insert into foods_episodes values(48, 63);
insert into foods values(49, 2, 'Cheerios');
insert into foods_episodes values(49, 133);
insert into foods values(50, 2, 'Corn Flakes');
insert into foods_episodes values(50, 89);
insert into foods_episodes values(50, 178);
insert into foods values(51, 2, 'Double Crunch');
insert into foods_episodes values(51, 52);
insert into foods values(52, 2, 'Fruit Loops');
insert into foods_episodes values(52, 163);
insert into foods values(53, 2, 'Grape Nuts');
insert into foods_episodes values(53, 178);
insert into foods values(54, 2, 'Honey Combs');
insert into foods_episodes values(54, 126);
insert into foods values(55, 2, 'Kasha');
insert into foods_episodes values(55, 73);
insert into foods_episodes values(55, 89);
insert into foods_episodes values(55, 103);
insert into foods_episodes values(55, 111);
insert into foods values(56, 2, 'Kix');
insert into foods_episodes values(56, 87);
insert into foods values(57, 2, 'Life');
insert into foods_episodes values(57, 178);
insert into foods values(58, 2, 'Pancakes');
insert into foods_episodes values(58, 80);
insert into foods values(59, 2, 'Reese''s Peanut-Butter Puffs');
insert into foods_episodes values(59, 101);
insert into foods values(60, 2, 'Rice Krispies');
insert into foods_episodes values(60, 140);
insert into foods values(61, 2, 'Special K');
insert into foods_episodes values(61, 178);
insert into foods values(62, 2, 'Tightly Wrapped Magic Pan Crepes');
insert into foods_episodes values(62, 150);
insert into foods values(63, 3, 'Broiled Chicken');
insert into foods_episodes values(63, 46);
insert into foods values(64, 3, 'Casserole');
insert into foods_episodes values(64, 101);
insert into foods values(65, 3, 'Chicken');
insert into foods_episodes values(65, 60);
insert into foods values(66, 3, 'Chicken (for wedding)');
insert into foods_episodes values(66, 132);
insert into foods values(67, 3, 'Chicken Cashew (not ordered)');
insert into foods_episodes values(67, 95);
insert into foods values(68, 3, 'Chicken Kiev');
insert into foods_episodes values(68, 142);
insert into foods values(69, 3, 'Kung-Pao Chicken');
insert into foods_episodes values(69, 104);
insert into foods values(70, 3, 'Chicken Marsala');
insert into foods_episodes values(70, 139);
insert into foods values(71, 3, 'Chicken Piccata');
insert into foods_episodes values(71, 139);
insert into foods values(72, 3, 'Chicken with Poppy Seeds');
insert into foods_episodes values(72, 125);
insert into foods values(73, 3, 'Chicken, whole stuffed w/Gorganzolla and Ham');
insert into foods_episodes values(73, 113);
insert into foods values(74, 3, 'Chicken Skins');
insert into foods_episodes values(74, 153);
insert into foods values(75, 3, 'Chicken Wing (Shoulder Blades)');
insert into foods_episodes values(75, 164);
insert into foods values(76, 3, 'Chicken (Kenny Rogers) ');
insert into foods_episodes values(76, 141);
insert into foods values(77, 3, 'Chicken (Tyler) ');
insert into foods_episodes values(77, 154);
insert into foods values(78, 3, 'Colonel Chang Chicken');
insert into foods_episodes values(78, 23);
insert into foods values(79, 3, 'Cornish Game Hen');
insert into foods_episodes values(79, 120);
insert into foods values(80, 3, 'Duck');
insert into foods_episodes values(80, 90);
insert into foods_episodes values(80, 139);
insert into foods values(81, 3, 'Duck, juicy breasts of');
insert into foods_episodes values(81, 29);
insert into foods values(82, 3, 'Turkey');
insert into foods_episodes values(82, 24);
insert into foods_episodes values(82, 161);
insert into foods values(83, 3, 'Turkey, Kramer');
insert into foods_episodes values(83, 156);
insert into foods values(84, 3, 'Turkey Jerky');
insert into foods_episodes values(84, 155);
insert into foods values(85, 3, 'Turkey Chili');
insert into foods_episodes values(85, 129);
insert into foods values(86, 4, 'A1 Sauce');
insert into foods_episodes values(86, 164);
insert into foods values(87, 4, 'Barbeque Sauce');
insert into foods_episodes values(87, 126);
insert into foods values(88, 4, 'Dijon Mustard');
insert into foods_episodes values(88, 122);
insert into foods values(89, 4, 'Dill');
insert into foods_episodes values(89, 40);
insert into foods values(90, 4, 'Ginger');
insert into foods_episodes values(90, 18);
insert into foods values(91, 4, 'Gravy');
insert into foods_episodes values(91, 131);
insert into foods_episodes values(91, 161);
insert into foods values(92, 4, 'Honey Mustard');
insert into foods_episodes values(92, 141);
insert into foods values(93, 4, 'Ketchup and Mustard together');
insert into foods_episodes values(93, 157);
insert into foods_episodes values(93, 178);
insert into foods values(94, 4, 'Ketchup');
insert into foods_episodes values(94, 67);
insert into foods_episodes values(94, 102);
insert into foods_episodes values(94, 20);
insert into foods_episodes values(94, 178);
insert into foods values(95, 4, 'Ketchup (secret)');
insert into foods_episodes values(95, 55);
insert into foods values(96, 4, 'Maple Syrup');
insert into foods_episodes values(96, 80);
insert into foods values(97, 4, 'Mustard (fancy)');
insert into foods_episodes values(97, 104);
insert into foods values(98, 4, 'Parsley');
insert into foods_episodes values(98, 161);
insert into foods_episodes values(98, 156);
insert into foods values(99, 4, 'Pepper');
insert into foods_episodes values(99, 171);
insert into foods values(100, 4, 'Pesto');
insert into foods_episodes values(100, 7);
insert into foods values(101, 4, 'Salad Dressing');
insert into foods_episodes values(101, 0);
insert into foods values(102, 4, 'Salsa');
insert into foods_episodes values(102, 42);
insert into foods values(103, 4, 'Tarragon');
insert into foods_episodes values(103, 40);
insert into foods values(104, 4, 'Tomatoe Sauce');
insert into foods_episodes values(104, 60);
insert into foods values(105, 4, 'Tomatoe Sauce (Hot and Spicey)');
insert into foods_episodes values(105, 150);
insert into foods values(106, 4, 'Oregano');
insert into foods_episodes values(106, 156);
insert into foods values(107, 4, 'Parmisan');
insert into foods_episodes values(107, 156);
insert into foods values(108, 5, 'Banana Yogurt');
insert into foods_episodes values(108, 161);
insert into foods values(109, 5, 'Butter');
insert into foods_episodes values(109, 156);
insert into foods values(110, 5, 'Danon Blueberry Yogurt');
insert into foods_episodes values(110, 66);
insert into foods values(111, 5, 'Egg Beaters Omelette with cottage cheese');
insert into foods_episodes values(111, 170);
insert into foods values(112, 5, 'Egg White Omelette');
insert into foods_episodes values(112, 87);
insert into foods_episodes values(112, 92);
insert into foods values(113, 5, 'Eggs for breakfast');
insert into foods_episodes values(113, 52);
insert into foods values(114, 5, 'Eggs');
insert into foods_episodes values(114, 144);
insert into foods values(115, 5, 'Egg Rolls');
insert into foods_episodes values(115, 10);
insert into foods values(116, 5, 'Egg Salad');
insert into foods_episodes values(116, 40);
insert into foods values(117, 5, 'Fete Cheese Omelette');
insert into foods_episodes values(117, 170);
insert into foods values(118, 5, 'French Toast');
insert into foods_episodes values(118, 14);
insert into foods values(119, 5, 'Large Block of Cheese');
insert into foods_episodes values(119, 120);
insert into foods_episodes values(119, 134);
insert into foods values(120, 5, 'Scambled Eggs with Lobster');
insert into foods_episodes values(120, 84);
insert into foods values(121, 5, 'Soft Boiled Egg');
insert into foods_episodes values(121, 52);
insert into foods values(122, 5, 'Swiss Cheese');
insert into foods_episodes values(122, 92);
insert into foods values(123, 5, 'Quiche thing');
insert into foods_episodes values(123, 113);
insert into foods values(124, 5, 'Western Omelette');
insert into foods_episodes values(124, 92);
insert into foods values(125, 6, 'Generic (as a meal)');
insert into foods_episodes values(125, 108);
insert into foods values(126, 6, 'Good Dip');
insert into foods_episodes values(126, 13);
insert into foods values(127, 6, 'Guacamole Dip');
insert into foods_episodes values(127, 58);
insert into foods values(128, 6, 'Hummus');
insert into foods_episodes values(128, 168);
insert into foods values(129, 7, 'Apple Cider');
insert into foods_episodes values(129, 130);
insert into foods values(130, 7, 'Arabian Mocha Java (beans)');
insert into foods_episodes values(130, 145);
insert into foods values(131, 7, 'Beaujolais');
insert into foods_episodes values(131, 76);
insert into foods values(132, 7, 'Beer');
insert into foods_episodes values(132, 67);
insert into foods_episodes values(132, 92);
insert into foods values(133, 7, 'Bosco');
insert into foods_episodes values(133, 116);
insert into foods_episodes values(133, 142);
insert into foods_episodes values(133, 8);
insert into foods values(134, 7, 'Cafe Latte');
insert into foods_episodes values(134, 111);
insert into foods_episodes values(134, 112);
insert into foods values(135, 7, 'Champagne Coolies');
insert into foods_episodes values(135, 128);
insert into foods values(136, 7, 'Chardonnay');
insert into foods_episodes values(136, 76);
insert into foods values(137, 7, 'Cider');
insert into foods_episodes values(137, 131);
insert into foods values(138, 7, 'Club Soda');
insert into foods_episodes values(138, 9);
insert into foods values(139, 7, 'Coca Cola');
insert into foods_episodes values(139, 142);
insert into foods values(140, 7, 'Cocoa');
insert into foods_episodes values(140, 172);
insert into foods values(141, 7, 'Coffe');
insert into foods_episodes values(141, 11);
insert into foods_episodes values(141, 30);
insert into foods values(142, 7, 'Colt 45');
insert into foods_episodes values(142, 25);
insert into foods_episodes values(142, 26);
insert into foods values(143, 7, 'Cream Soda');
insert into foods_episodes values(143, 159);
insert into foods values(144, 7, 'Cranberry juice with two limes');
insert into foods_episodes values(144, 9);
insert into foods values(145, 7, 'Decaf Coffee');
insert into foods_episodes values(145, 0);
insert into foods_episodes values(145, 92);
insert into foods values(146, 7, 'Decaf Cappaccino');
insert into foods_episodes values(146, 43);
insert into foods_episodes values(146, 42);
insert into foods_episodes values(146, 36);
insert into foods values(147, 7, 'Dr. Pepper (diet)');
insert into foods_episodes values(147, 175);
insert into foods values(148, 7, 'Duty Free Kalua');
insert into foods_episodes values(148, 156);
insert into foods values(149, 7, 'Folger''s Crystals');
insert into foods_episodes values(149, 21);
insert into foods values(150, 7, 'Gatorade');
insert into foods_episodes values(150, 31);
insert into foods values(151, 7, 'Grape Juice');
insert into foods_episodes values(151, 90);
insert into foods values(152, 7, 'Morning Thunder (with caffine)');
insert into foods_episodes values(152, 20);
insert into foods values(153, 7, 'Hennigen''s');
insert into foods_episodes values(153, 27);
insert into foods_episodes values(153, 139);
insert into foods_episodes values(153, 38);
insert into foods values(154, 7, 'Hershey''s');
insert into foods_episodes values(154, 116);
insert into foods values(155, 7, 'Hot Coffee');
insert into foods_episodes values(155, 112);
insert into foods values(156, 7, 'Juice box');
insert into foods_episodes values(156, 134);
insert into foods values(157, 7, 'Latte');
insert into foods_episodes values(157, 112);
insert into foods values(158, 7, 'Mellow Yellow soda');
insert into foods_episodes values(158, 130);
insert into foods values(159, 7, 'Merlot');
insert into foods_episodes values(159, 120);
insert into foods values(160, 7, 'Milk');
insert into foods_episodes values(160, 142);
insert into foods_episodes values(160, 141);
insert into foods values(161, 7, 'Milkshake');
insert into foods_episodes values(161, 178);
insert into foods values(162, 7, 'Molotov Cocktail');
insert into foods_episodes values(162, 14);
insert into foods values(163, 7, 'Morning Thunder (with caffein)');
insert into foods_episodes values(163, 20);
insert into foods values(164, 7, 'Naya Water');
insert into foods_episodes values(164, 73);
insert into foods_episodes values(164, 80);
insert into foods_episodes values(164, 160);
insert into foods values(165, 7, 'Nestle''s Quick');
insert into foods_episodes values(165, 139);
insert into foods values(166, 7, 'Orange Juice');
insert into foods_episodes values(166, 80);
insert into foods_episodes values(166, 113);
insert into foods values(167, 7, 'Ovaltine');
insert into foods_episodes values(167, 139);
insert into foods values(168, 7, 'Peach Schnapps');
insert into foods_episodes values(168, 163);
insert into foods values(169, 7, 'Pepsi');
insert into foods_episodes values(169, 76);
insert into foods_episodes values(169, 19);
insert into foods values(170, 7, 'Pertussin with Club Soda');
insert into foods_episodes values(170, 84);
insert into foods values(171, 7, 'Postum');
insert into foods_episodes values(171, 31);
insert into foods values(172, 7, 'Prune Juice');
insert into foods_episodes values(172, 73);
insert into foods values(173, 7, 'Royal Crown Cola');
insert into foods_episodes values(173, 175);
insert into foods values(174, 7, 'Sanka');
insert into foods_episodes values(174, 92);
insert into foods values(175, 7, 'Scotch');
insert into foods_episodes values(175, 9);
insert into foods values(176, 7, 'Seltzer');
insert into foods_episodes values(176, 42);
insert into foods values(177, 7, 'Snapple');
insert into foods_episodes values(177, 49);
insert into foods_episodes values(177, 142);
insert into foods values(178, 7, 'Sour milk out of the carton');
insert into foods_episodes values(178, 42);
insert into foods values(179, 7, 'Tea');
insert into foods_episodes values(179, 114);
insert into foods values(180, 7, 'Tomato Juice');
insert into foods_episodes values(180, 60);
insert into foods values(181, 7, 'Tropicana Orange Juice');
insert into foods_episodes values(181, 80);
insert into foods values(182, 7, 'Vodka');
insert into foods_episodes values(182, 146);
insert into foods values(183, 7, 'Vodka and Cranberry Juice');
insert into foods_episodes values(183, 28);
insert into foods values(184, 7, 'Water, bottled');
insert into foods_episodes values(184, 70);
insert into foods values(185, 7, 'Wild Turkey');
insert into foods_episodes values(185, 114);
insert into foods values(186, 7, 'Wine, boxed');
insert into foods_episodes values(186, 76);
insert into foods values(187, 7, 'Wine');
insert into foods_episodes values(187, 161);
insert into foods values(188, 7, 'Yoo Hoo');
insert into foods_episodes values(188, 46);
insert into foods values(189, 8, 'Apple');
insert into foods_episodes values(189, 11);
insert into foods_episodes values(189, 122);
insert into foods values(190, 8, 'Apple Pie');
insert into foods_episodes values(190, 78);
insert into foods values(191, 8, 'Avacado');
insert into foods_episodes values(191, 64);
insert into foods values(192, 8, 'Banana');
insert into foods_episodes values(192, 108);
insert into foods_episodes values(192, 122);
insert into foods_episodes values(192, 164);
insert into foods values(193, 8, 'Canned Fruit');
insert into foods_episodes values(193, 112);
insert into foods values(194, 8, 'Cantaloupe');
insert into foods_episodes values(194, 64);
insert into foods_episodes values(194, 66);
insert into foods_episodes values(194, 5);
insert into foods values(195, 8, 'Grape');
insert into foods_episodes values(195, 4);
insert into foods values(196, 8, 'Grapefruit');
insert into foods_episodes values(196, 113);
insert into foods_episodes values(196, 30);
insert into foods values(197, 8, 'Hamptons Tomatoes');
insert into foods_episodes values(197, 84);
insert into foods values(198, 8, 'Macinaw peaches');
insert into foods_episodes values(198, 105);
insert into foods values(199, 8, 'Mangos');
insert into foods_episodes values(199, 64);
insert into foods values(200, 8, 'Melons');
insert into foods_episodes values(200, 59);
insert into foods values(201, 8, 'Nectarine');
insert into foods_episodes values(201, 158);
insert into foods values(202, 8, 'Oranges');
insert into foods_episodes values(202, 140);
insert into foods values(203, 8, 'Papaya');
insert into foods_episodes values(203, 64);
insert into foods_episodes values(203, 66);
insert into foods values(204, 8, 'Peaches');
insert into foods_episodes values(204, 64);
insert into foods values(205, 8, 'Pineapple');
insert into foods_episodes values(205, 178);
insert into foods values(206, 8, 'Plantains');
insert into foods_episodes values(206, 64);
insert into foods values(207, 8, 'Plumbs');
insert into foods_episodes values(207, 64);
insert into foods values(208, 8, 'Prunes, Figs, any Dried Fruit');
insert into foods_episodes values(208, 63);
insert into foods values(209, 8, 'Raisins');
insert into foods_episodes values(209, 62);
insert into foods values(210, 8, 'Shredded Coconut');
insert into foods_episodes values(210, 156);
insert into foods values(211, 8, 'Strawberries with Chocolate Sauce');
insert into foods_episodes values(211, 159);
insert into foods values(212, 9, 'Almond Joy');
insert into foods_episodes values(212, 88);
insert into foods values(213, 9, 'All Day Sucker');
insert into foods_episodes values(213, 163);
insert into foods values(214, 9, 'Big Hunk');
insert into foods_episodes values(214, 151);
insert into foods values(215, 9, 'Black Jacks - black licorice gum');
insert into foods_episodes values(215, 21);
insert into foods values(216, 9, 'Bubble Gum');
insert into foods_episodes values(216, 46);
insert into foods values(217, 9, 'Candy Apple');
insert into foods_episodes values(217, 143);
insert into foods values(218, 9, 'Cashew Nuts');
insert into foods_episodes values(218, 105);
insert into foods values(219, 9, 'Cashews (bag of)');
insert into foods_episodes values(219, 7);
insert into foods values(220, 9, 'Clark Bar');
insert into foods_episodes values(220, 76);
insert into foods values(221, 9, 'Chinese Chewing Gum');
insert into foods_episodes values(221, 119);
insert into foods values(222, 9, 'Chocolates, box of');
insert into foods_episodes values(222, 80);
insert into foods values(223, 9, 'Chocolate Chip Mint');
insert into foods_episodes values(223, 132);
insert into foods values(224, 9, 'Chocolate Covered Cherries');
insert into foods_episodes values(224, 2);
insert into foods values(225, 9, 'Chuckles (5 flavors)');
insert into foods_episodes values(225, 15);
insert into foods_episodes values(225, 87);
insert into foods values(226, 9, 'Chunky Bar');
insert into foods_episodes values(226, 105);
insert into foods values(227, 9, 'Cracker Jacks');
insert into foods_episodes values(227, 83);
insert into foods values(228, 9, 'Cupcakes (upsidedown)');
insert into foods_episodes values(228, 104);
insert into foods values(229, 9, 'Dentyne');
insert into foods_episodes values(229, 21);
insert into foods values(230, 9, 'Double Crunch Ice Cream');
insert into foods_episodes values(230, 52);
insert into foods values(231, 9, 'Double Fudge Sundae');
insert into foods_episodes values(231, 135);
insert into foods values(232, 9, 'Doublemint Gum');
insert into foods_episodes values(232, 78);
insert into foods values(233, 9, 'Frozen Yogurt');
insert into foods_episodes values(233, 70);
insert into foods values(234, 9, 'Godiva Chocolates');
insert into foods_episodes values(234, 75);
insert into foods values(235, 9, 'Gum');
insert into foods_episodes values(235, 75);
insert into foods_episodes values(235, 168);
insert into foods values(236, 9, 'Jucyfruit Gum');
insert into foods_episodes values(236, 144);
insert into foods values(237, 9, 'Haagen Dazs');
insert into foods_episodes values(237, 63);
insert into foods values(238, 9, 'Hot Fudge Sundae');
insert into foods_episodes values(238, 69);
insert into foods values(239, 9, 'Ice Cream');
insert into foods_episodes values(239, 15);
insert into foods_episodes values(239, 175);
insert into foods values(240, 9, 'Ice Cream (Breyer''s vanilla)');
insert into foods_episodes values(240, 14);
insert into foods values(241, 9, 'Ice Cream Triple Minute Man');
insert into foods_episodes values(241, 164);
insert into foods values(242, 9, 'Ice Cream Rum and Raisin');
insert into foods_episodes values(242, 164);
insert into foods values(243, 9, 'Jello with Bananas');
insert into foods_episodes values(243, 65);
insert into foods values(244, 9, 'JujyFruit');
insert into foods_episodes values(244, 85);
insert into foods values(245, 9, 'Junior Mints');
insert into foods_episodes values(245, 59);
insert into foods values(246, 9, 'Klondike Bars');
insert into foods_episodes values(246, 102);
insert into foods values(247, 9, 'M and M''s');
insert into foods_episodes values(247, 88);
insert into foods_episodes values(247, 135);
insert into foods values(248, 9, 'Macadamia Nuts');
insert into foods_episodes values(248, 105);
insert into foods values(249, 9, 'Mints');
insert into foods_episodes values(249, 40);
insert into foods_episodes values(249, 168);
insert into foods values(250, 9, 'Mr. Goodbar');
insert into foods_episodes values(250, 104);
insert into foods values(251, 9, 'Nutrageous');
insert into foods_episodes values(251, 151);
insert into foods values(252, 9, 'Nuts, Filbert and Hazel');
insert into foods_episodes values(252, 90);
insert into foods values(253, 9, 'Oh Henry Bar');
insert into foods_episodes values(253, 121);
insert into foods values(254, 9, 'Peanut Butter');
insert into foods_episodes values(254, 92);
insert into foods values(255, 9, 'Peanuts');
insert into foods_episodes values(255, 157);
insert into foods values(256, 9, 'Pecan');
insert into foods_episodes values(256, 105);
insert into foods values(257, 9, 'Pez');
insert into foods_episodes values(257, 31);
insert into foods values(258, 9, 'Pineapple Italian Ice');
insert into foods_episodes values(258, 109);
insert into foods values(259, 9, 'Popcorn');
insert into foods_episodes values(259, 85);
insert into foods values(260, 9, 'Pretzels (unsalted)');
insert into foods_episodes values(260, 93);
insert into foods values(261, 9, 'Pretzels (salted)');
insert into foods_episodes values(261, 27);
insert into foods values(262, 9, 'Pudding Skins');
insert into foods_episodes values(262, 159);
insert into foods values(263, 9, 'Ring Dings');
insert into foods_episodes values(263, 76);
insert into foods_episodes values(263, 66);
insert into foods values(264, 9, 'Rold Gold Pretzles');
insert into foods_episodes values(264, 66);
insert into foods values(265, 9, 'Snackwells');
insert into foods_episodes values(265, 111);
insert into foods values(266, 9, 'Snickers');
insert into foods_episodes values(266, 88);
insert into foods values(267, 9, 'Three Musketeers');
insert into foods_episodes values(267, 154);
insert into foods values(268, 9, 'Tic Tacs');
insert into foods_episodes values(268, 161);
insert into foods_episodes values(268, 50);
insert into foods_episodes values(268, 40);
insert into foods values(269, 9, 'Tootsie Pop');
insert into foods_episodes values(269, 169);
insert into foods values(270, 9, 'Twinkies');
insert into foods_episodes values(270, 151);
insert into foods values(271, 9, 'Twix Bar');
insert into foods_episodes values(271, 166);
insert into foods values(272, 9, 'Wheat Thins (reduced fat)');
insert into foods_episodes values(272, 123);
insert into foods values(273, 10, 'Arby''s Roast Beef');
insert into foods_episodes values(273, 166);
insert into foods_episodes values(273, 171);
insert into foods values(274, 10, 'Bacon');
insert into foods_episodes values(274, 135);
insert into foods values(275, 10, 'Beef-A-Reeno');
insert into foods_episodes values(275, 120);
insert into foods values(276, 10, 'Brisket');
insert into foods_episodes values(276, 139);
insert into foods values(277, 10, 'Chili');
insert into foods_episodes values(277, 92);
insert into foods values(278, 10, 'Cold-cuts');
insert into foods_episodes values(278, 162);
insert into foods values(279, 10, 'Dog Food');
insert into foods_episodes values(279, 29);
insert into foods values(280, 10, 'Five Alarm Chili');
insert into foods_episodes values(280, 90);
insert into foods values(281, 10, 'Franks and Beans');
insert into foods_episodes values(281, 24);
insert into foods values(282, 10, 'Gyro');
insert into foods_episodes values(282, 73);
insert into foods values(283, 10, 'Hamburger (Meduim)');
insert into foods_episodes values(283, 125);
insert into foods values(284, 10, 'Hamburger (Skyburger)');
insert into foods_episodes values(284, 10);
insert into foods values(285, 10, 'Hamburger');
insert into foods_episodes values(285, 178);
insert into foods values(286, 10, 'Hash');
insert into foods_episodes values(286, 139);
insert into foods values(287, 10, 'Sausages (homemade)');
insert into foods_episodes values(287, 159);
insert into foods values(288, 10, 'Hot Dog');
insert into foods_episodes values(288, 119);
insert into foods_episodes values(288, 109);
insert into foods_episodes values(288, 148);
insert into foods_episodes values(288, 170);
insert into foods_episodes values(288, 92);
insert into foods values(289, 10, 'Hot Dog (Papaya King)');
insert into foods_episodes values(289, 53);
insert into foods values(290, 10, 'Hot Dog (Nathan''s)');
insert into foods_episodes values(290, 30);
insert into foods values(291, 10, 'Hot Dog (phone)');
insert into foods_episodes values(291, 143);
insert into foods values(292, 10, 'Lamb Chops');
insert into foods_episodes values(292, 113);
insert into foods values(293, 10, 'Meat Loaf');
insert into foods_episodes values(293, 1);
insert into foods values(294, 10, 'Meatball Sandwich');
insert into foods_episodes values(294, 144);
insert into foods values(295, 10, 'Mutton');
insert into foods_episodes values(295, 113);
insert into foods_episodes values(295, 131);
insert into foods values(296, 10, 'Pastrami');
insert into foods_episodes values(296, 95);
insert into foods values(297, 10, 'Corned Beef');
insert into foods_episodes values(297, 95);
insert into foods values(298, 10, 'Salami');
insert into foods_episodes values(298, 95);
insert into foods_episodes values(298, 15);
insert into foods values(299, 10, 'Bologna');
insert into foods_episodes values(299, 95);
insert into foods_episodes values(299, 15);
insert into foods values(300, 10, 'Pork Chops');
insert into foods_episodes values(300, 113);
insert into foods values(301, 10, 'Porterhouse Steak');
insert into foods_episodes values(301, 113);
insert into foods values(302, 10, 'Red Meat');
insert into foods_episodes values(302, 94);
insert into foods values(303, 10, 'Salted Cured Meats');
insert into foods_episodes values(303, 159);
insert into foods values(304, 10, 'Steak');
insert into foods_episodes values(304, 29);
insert into foods_episodes values(304, 164);
insert into foods values(305, 10, 'Stuffed Cabbage');
insert into foods_episodes values(305, 139);
insert into foods values(306, 10, 'Steak (T-Bone)');
insert into foods_episodes values(306, 174);
insert into foods values(307, 10, 'Tamale');
insert into foods_episodes values(307, 144);
insert into foods values(308, 10, 'Steak (US Prime)');
insert into foods_episodes values(308, 139);
insert into foods values(309, 11, 'Calzone (Paisano''s)');
insert into foods_episodes values(309, 129);
insert into foods values(310, 11, 'Canolli');
insert into foods_episodes values(310, 129);
insert into foods values(311, 11, 'Chow Fung (noodle)');
insert into foods_episodes values(311, 49);
insert into foods values(312, 11, 'Macaroni');
insert into foods_episodes values(312, 109);
insert into foods values(313, 11, 'Fusilli');
insert into foods_episodes values(313, 106);
insert into foods values(314, 11, 'Paella');
insert into foods_episodes values(314, 81);
insert into foods values(315, 11, 'Pasta Primavera');
insert into foods_episodes values(315, 55);
insert into foods values(316, 11, 'Pasta at Chadways');
insert into foods_episodes values(316, 27);
insert into foods values(317, 11, 'Pizza');
insert into foods_episodes values(317, 67);
insert into foods_episodes values(317, 90);
insert into foods_episodes values(317, 1);
insert into foods_episodes values(317, 173);
insert into foods values(318, 11, 'Pizza (Paccino''s)');
insert into foods_episodes values(318, 90);
insert into foods values(319, 11, 'Raviolli');
insert into foods_episodes values(319, 106);
insert into foods values(320, 11, 'Rigatoni');
insert into foods_episodes values(320, 24);
insert into foods values(321, 11, 'Rissoto');
insert into foods_episodes values(321, 96);
insert into foods_episodes values(321, 64);
insert into foods values(322, 11, 'Spaghetti');
insert into foods_episodes values(322, 62);
insert into foods_episodes values(322, 59);
insert into foods values(323, 11, 'Tamales');
insert into foods_episodes values(323, 42);
insert into foods values(324, 11, 'Vegetable Lasagna');
insert into foods_episodes values(324, 156);
insert into foods values(325, 12, 'Atomic Sub');
insert into foods_episodes values(325, 165);
insert into foods values(326, 12, 'Bologna');
insert into foods_episodes values(326, 65);
insert into foods_episodes values(326, 85);
insert into foods values(327, 12, 'Bacon Club (no turkey)');
insert into foods_episodes values(327, 92);
insert into foods values(328, 12, 'BLT');
insert into foods_episodes values(328, 3);
insert into foods values(329, 12, 'Brisket Sandwich');
insert into foods_episodes values(329, 3);
insert into foods values(330, 12, 'Chicken Salad on Rye');
insert into foods_episodes values(330, 85);
insert into foods values(331, 12, 'Cold Chicken');
insert into foods_episodes values(331, 92);
insert into foods values(332, 12, 'Egg Salad');
insert into foods_episodes values(332, 4);
insert into foods_episodes values(332, 40);
insert into foods_episodes values(332, 1);
insert into foods values(333, 12, 'Grilled Cheese');
insert into foods_episodes values(333, 134);
insert into foods_episodes values(333, 64);
insert into foods values(334, 12, 'Ham and Cheese');
insert into foods_episodes values(334, 104);
insert into foods values(335, 12, 'Hero Sandwich');
insert into foods_episodes values(335, 78);
insert into foods values(336, 12, 'Little sandwiches');
insert into foods_episodes values(336, 75);
insert into foods values(337, 12, 'Ostrich Burger');
insert into foods_episodes values(337, 174);
insert into foods values(338, 12, 'Pastrami Sandwich');
insert into foods_episodes values(338, 159);
insert into foods values(339, 12, 'Peanut Butter');
insert into foods_episodes values(339, 75);
insert into foods values(340, 12, 'Reuben');
insert into foods_episodes values(340, 157);
insert into foods values(341, 12, 'Salami Sandwich');
insert into foods_episodes values(341, 141);
insert into foods values(342, 12, 'Salmon');
insert into foods_episodes values(342, 75);
insert into foods values(343, 12, 'Tuna');
insert into foods_episodes values(343, 75);
insert into foods_episodes values(343, 40);
insert into foods values(344, 12, 'Tuna on toast');
insert into foods_episodes values(344, 85);
insert into foods_episodes values(344, 92);
insert into foods values(345, 12, 'Turkey Club');
insert into foods_episodes values(345, 46);
insert into foods_episodes values(345, 170);
insert into foods_episodes values(345, 92);
insert into foods values(346, 12, 'Turkey Roll');
insert into foods_episodes values(346, 1);
insert into foods values(347, 12, 'Turkey Sandwich');
insert into foods_episodes values(347, 174);
insert into foods_episodes values(347, 122);
insert into foods_episodes values(347, 109);
insert into foods values(348, 13, 'Clams Casino');
insert into foods_episodes values(348, 163);
insert into foods values(349, 13, 'Crab Legs');
insert into foods_episodes values(349, 130);
insert into foods values(350, 13, 'Flounder Supreme - #47');
insert into foods_episodes values(350, 149);
insert into foods values(351, 13, 'Halibut');
insert into foods_episodes values(351, 15);
insert into foods values(352, 13, 'Lobster');
insert into foods_episodes values(352, 84);
insert into foods_episodes values(352, 106);
insert into foods_episodes values(352, 136);
insert into foods values(353, 13, 'Lobster on Monk''s menu');
insert into foods_episodes values(353, 106);
insert into foods values(354, 13, 'Lobster Shells');
insert into foods_episodes values(354, 153);
insert into foods values(355, 13, 'Salmon');
insert into foods_episodes values(355, 85);
insert into foods_episodes values(355, 92);
insert into foods values(356, 13, 'Sardines');
insert into foods_episodes values(356, 36);
insert into foods values(357, 13, 'Shrimp');
insert into foods_episodes values(357, 146);
insert into foods_episodes values(357, 143);
insert into foods_episodes values(357, 24);
insert into foods values(358, 13, 'Sole');
insert into foods_episodes values(358, 92);
insert into foods values(359, 13, 'Swordfish');
insert into foods_episodes values(359, 92);
insert into foods values(360, 13, 'Tuna Fishy');
insert into foods_episodes values(360, 115);
insert into foods values(361, 13, 'Whitefish');
insert into foods_episodes values(361, 135);
insert into foods values(362, 14, 'Bouillabaisse');
insert into foods_episodes values(362, 2);
insert into foods_episodes values(362, 55);
insert into foods values(363, 14, 'Carrot Soup');
insert into foods_episodes values(363, 69);
insert into foods values(364, 14, 'Chicken Gumbo');
insert into foods_episodes values(364, 115);
insert into foods_episodes values(364, 92);
insert into foods values(365, 14, 'Consommé');
insert into foods_episodes values(365, 92);
insert into foods values(366, 14, 'Crab Bisque');
insert into foods_episodes values(366, 115);
insert into foods values(367, 14, 'Creamed Soups');
insert into foods_episodes values(367, 118);
insert into foods values(368, 14, 'Cuppa Soup');
insert into foods_episodes values(368, 161);
insert into foods values(369, 14, 'Deli Soup');
insert into foods_episodes values(369, 77);
insert into foods values(370, 14, 'Jambalaya');
insert into foods_episodes values(370, 115);
insert into foods values(371, 14, 'Lobster Bisque');
insert into foods_episodes values(371, 152);
insert into foods values(372, 14, 'Lima Bean Soup');
insert into foods_episodes values(372, 115);
insert into foods values(373, 14, 'Motzah Ball');
insert into foods_episodes values(373, 92);
insert into foods values(374, 14, 'Medium Turkey Chili');
insert into foods_episodes values(374, 115);
insert into foods values(375, 14, 'Mulligatawny soup');
insert into foods_episodes values(375, 115);
insert into foods values(376, 14, 'Mushroom Barley');
insert into foods_episodes values(376, 92);
insert into foods values(377, 14, 'Pea Soup');
insert into foods_episodes values(377, 69);
insert into foods values(378, 14, 'Tomatoe Soup');
insert into foods_episodes values(378, 92);
insert into foods values(379, 14, 'Wild Mushroom');
insert into foods_episodes values(379, 115);
insert into foods values(380, 14, 'Yankee Bean');
insert into foods_episodes values(380, 27);
insert into foods values(381, 15, 'Artichokes');
insert into foods_episodes values(381, 130);
insert into foods values(382, 15, 'Baked Beans');
insert into foods_episodes values(382, 173);
insert into foods values(383, 15, 'Baked Potato w/Sour Cream');
insert into foods_episodes values(383, 113);
insert into foods values(384, 15, 'Big Salad');
insert into foods_episodes values(384, 87);
insert into foods_episodes values(384, 92);
insert into foods values(385, 15, 'Brocolli');
insert into foods_episodes values(385, 141);
insert into foods values(386, 15, 'Chef Salad');
insert into foods_episodes values(386, 174);
insert into foods values(387, 15, 'Carrots');
insert into foods_episodes values(387, 69);
insert into foods values(388, 15, 'Cole Slaw');
insert into foods_episodes values(388, 85);
insert into foods values(389, 15, 'Cucumber');
insert into foods_episodes values(389, 15);
insert into foods values(390, 15, 'Egg Plant');
insert into foods_episodes values(390, 129);
insert into foods_episodes values(390, 178);
insert into foods values(391, 15, 'Foliage (edible)');
insert into foods_episodes values(391, 6);
insert into foods values(392, 15, 'French Fries');
insert into foods_episodes values(392, 30);
insert into foods values(393, 15, 'French Fried Onion Rings');
insert into foods_episodes values(393, 29);
insert into foods values(394, 15, 'Hampton Tomatoes');
insert into foods_episodes values(394, 84);
insert into foods values(395, 15, 'Insalata Grande');
insert into foods_episodes values(395, 142);
insert into foods values(396, 15, 'Kugel');
insert into foods_episodes values(396, 139);
insert into foods values(397, 15, 'Kreplach');
insert into foods_episodes values(397, 139);
insert into foods values(398, 15, 'Latkas');
insert into foods_episodes values(398, 139);
insert into foods values(399, 15, 'Lettuce (as a brain)');
insert into foods_episodes values(399, 142);
insert into foods values(400, 15, 'Olives');
insert into foods_episodes values(400, 80);
insert into foods_episodes values(400, 136);
insert into foods values(401, 15, 'Onion');
insert into foods_episodes values(401, 66);
insert into foods_episodes values(401, 135);
insert into foods values(402, 15, 'Peas');
insert into foods_episodes values(402, 6);
insert into foods_episodes values(402, 69);
insert into foods values(403, 15, 'Pea Pods');
insert into foods_episodes values(403, 49);
insert into foods_episodes values(403, 54);
insert into foods values(404, 15, 'Pickle');
insert into foods_episodes values(404, 15);
insert into foods values(405, 15, 'Potato Salad');
insert into foods_episodes values(405, 85);
insert into foods_episodes values(405, 172);
insert into foods values(406, 15, 'Potatoes');
insert into foods_episodes values(406, 162);
insert into foods values(407, 15, 'Radish Roses');
insert into foods_episodes values(407, 164);
insert into foods values(408, 15, 'Roasted Potatoes');
insert into foods_episodes values(408, 14);
insert into foods values(409, 15, 'Salad');
insert into foods_episodes values(409, 87);
insert into foods_episodes values(409, 92);
insert into foods values(410, 15, 'Tzimmis');
insert into foods_episodes values(410, 139);
insert into foods values(411, 15, 'Veggie burger');
insert into foods_episodes values(411, 61);
insert into foods values(412, 15, 'Wax Beans (Generic brand)');
insert into foods_episodes values(412, 161);
