@startuml note
' 可以用 note left of , note right of , note top of , note bottom of 等关键字给一个对象添加注释。
' 注释还可以通过 note 关键字来定义,然后用.. 连接其他对象。
:Main Admin: as Admin
(Use the application) as (Use)
User -> (Start)
User --> (Use)
Admin ---> (Use)
note right of Admin : This is an example.
note right of (Use)
A note can also
be on several lines
end note
note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml