#include	"unpipc.h"		/* our header */
#include	"square.h"		/* generated by rpcgen */

int
main(int argc, char **argv)
{
	CLIENT		*cl;
	struct timeval tv;

	if (argc != 3)
		err_quit("usage: client <hostname> <protocol>");

	cl = Clnt_create(argv[1], SQUARE_PROG, SQUARE_VERS, argv[2]);

	tv.tv_sec = 10;
	tv.tv_usec = 0;
	if (clnt_call(cl, NULLPROC, xdr_void, NULL,
				  xdr_void, NULL, tv) != RPC_SUCCESS)
		err_quit("%s", clnt_sperror(cl, argv[1]));

	exit(0);
}
