@startuml note_simple

' 模板通过类关键字 ("<<" 和">>") 来定义
' 你可以使用 note left of , note right of , note top of , note bottom of 这些关键字来添加备注。
' 你还可以在类的声明末尾使用 note left, note right,note top, note bottom 来添加备注。
' 此外,单独用 note 这个关键字也是可以的,使用 .. 符号可以作出一条连接它与其它对象的虚线。

class Object << general >>
Object <|--- ArrayList
note top of Object : In java, every class\nextends this one.
note "This is a floating note" as N1
note "This note is connected\nto several objects." as N2
Object .. N2
N2 .. ArrayList
class Foo
note left: On last defined class
@enduml 