@startuml arrow_direction 
/'
使用 -> 定义水平箭头,也可以使用下列格式强制设置箭头方向:
• -down-> (default arrow)
• -right-> or ->
• -left->
• -up->
'/
[*] -up-> First
First -right-> Second
Second --> Third
Third -left-> Last
@enduml