/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST1_H_RPCGEN
#define	_TEST1_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


struct optlong {
	int discr;
	union {
		long val;
	} optlong_u;
};
typedef struct optlong optlong;

struct args {
	optlong arg0;
	struct {
		u_int arg1_len;
		long *arg1_val;
	} arg1;
	short *arg2;
};
typedef struct args args;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_optlong(XDR *, optlong*);
extern  bool_t xdr_args(XDR *, args*);

#else /* K&R C */
extern bool_t xdr_optlong();
extern bool_t xdr_args();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST1_H_RPCGEN */
