include ../Makefile.inc

EXE = getdaytimetcpclient  getdaytimeclientv6 putdaytimesrv






all : ${EXE}

clean : 
	${RM} ${EXE} *.o

showall :
	@ echo ${EXE}

#${EXE} : ${TLPI_LIB}		# True as a rough approximation
