@startuml list
/'
Some HTML tags are also working:
• <b> for bold text
• <u> or <u:#AAAAAA> or <u:colorName> for underline
• <i> for italic
• <s> or <s:#AAAAAA> or <s:colorName> for strike text
• <w> or <w:#AAAAAA> or <w:colorName> for wave underline text
• <color:#AAAAAA> or <color:colorName>
• <back:#AAAAAA> or <back:colorName> for background color
• <size:nn> to change font size
• <img:file> : the file must be accessible by the filesystem
• <img:http://plantuml.com/logo3.png> : the URL must be available from the Internet
'/

:* You can change <color:red>text color</color>
* You can change <back:cadetblue>background color</back>
* You can change <size:18>size</size>
* You use <u>legacy</u> <b>HTML <i>tag</i></b>
* You use <u:red>color</u> <s:green>in HTML</s> <w:#0000FF>tag</w>
----
* Use image : <img:http://plantuml.com/logo3.png>;


/'
listopeniconic
'/

@enduml